### ISSUE TITLE
新功能建议-留言功能

### ISSUE THREAD

**Issue by zyh001** [axiref/telegram-pwsbot#1]
建议加入用户留言功能，实现用户与后台人员的交互！

**Comment by axiref** [comment]
目前主要是投稿机器人，用户可以投递给频道，然后管理员可透过`/re`命令发送消息，自动进入对话模式和用户交谈。
目前是这样，能够实现交互对话的功能
若阁下有更好之建议，可以提供

**Comment by zyh001** [comment]
@axiref 非常感谢作者的回复。我的想法是，用户也可以通过一个命令来与管理员发起会话，便于用户与管理员交流。不过目前已经很好用了，我只是渴望加入一些新功能而已。再次感谢作者开发出这么好用的机器人😉
